# Generated by Django 2.1.3 on 2018-11-26 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_id', models.UUIDField(db_column='kategori_number', default=uuid.uuid4, unique=True)),
                ('tanya', models.TextField(blank=True)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.UUIDField(db_column='question_number', default=uuid.uuid4, editable=False, unique=True)),
                ('jawaban', models.TextField(blank=True)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('kategories', models.ManyToManyField(db_column='kategories_id', to='kuisioner.Kategori')),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
