# Generated by Django 2.1.3 on 2018-11-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuisioner', '0002_auto_20181126_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='kuisioner.Question')),
            ],
            options={
                'db_table': 'survey',
            },
        ),
    ]
