# Generated by Django 2.1.3 on 2018-12-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuisioner', '0004_survey_crated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='kategories',
            field=models.ForeignKey(db_column='kuestion_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='kuisioner.Kategori'),
        ),
    ]
