# Generated by Django 2.1.3 on 2018-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20181121_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='kategori_id',
            field=models.CharField(db_column='kategori_number', default='ewpy2cau', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(db_column='question_number', default='elkw2w9r', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='total',
            field=models.CharField(db_column='total_number', default='fkomkuqb', max_length=6, unique=True),
        ),
    ]
