# Generated by Django 2.1.3 on 2018-11-21 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20181121_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='kategori_id',
            field=models.UUIDField(db_column='kategori_number', default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.UUIDField(db_column='question_number', default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='total',
            field=models.UUIDField(db_column='total_number', default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
